### ISSUE TITLE
Incorrect cntbn.cc values

### ISSUE THREAD

**Issue by joewdavies** [eurostat/Nuts2json#45]
It seems that some cntbn features do not have the correct cc property:

![image](https://github.com/user-attachments/assets/f690abd3-d8c4-4b86-b9e5-7571655a42e3)

I discovered this while testing CSS in eurostat-map by targeting and hiding boundary elements that had 'oth' but not 'co' or 'cc':
```css
            .em-bn-oth:not(.em-bn-co):not(.em-bn-cc) {
                stroke-width: 0 !important;
            }
```

![image](https://github.com/user-attachments/assets/ea2db876-8963-4c95-a165-59bce8be7abc)

I would seem that (at least for NUTS2) all cntbn have cc set to F
